sudo: required
language: csharp
os: windows

mono: none
#dotnet: 2.0.0

branches:
  only:
    - master
    - /.*/


script: 
  - echo $TRAVIS_BRANCH
  - echo $TRAVIS_PULL_REQUEST
  - echo $TRAVIS_PULL_REQUEST_BRANCH
  - echo $TRAVIS_PULL_REQUEST_SHA
  - echo $STABLE
  - dotnet restore ./src/ReactiveDomain.sln
  - dotnet msbuild ./src/ReactiveDomain.sln
  - dotnet test ./src/ReactiveDomain.Messaging.Tests/ReactiveDomain.Messaging.Tests.csproj
  - dotnet test ./src/ReactiveDomain.Foundation.Tests/ReactiveDomain.Foundation.Tests.csproj  
  - dotnet test ./src/ReactiveDomain.PrivateLedger.Tests/ReactiveDomain.PrivateLedger.Tests.csproj
  - dotnet test ./src/ReactiveDomain.Transport.Tests/ReactiveDomain.Transport.Tests.csproj
  - if [[ $TRAVIS_BRANCH = update-nuspec-for-builds ]]; then echo 'This is master after success'; fi;

#after_success:  
 # - if [[ $TRAVIS_BRANCH = master ]]; then echo 'This is master after success'; fi;
 # - if [[ $TRAVIS_BRANCH = master && $TRAVIS_EVENT_TYPE = push ]]; then echo "Master and Push";
 # - if [[ $TRAVIS_BRANCH = master && $STABLE = true && $TRAVIS_EVENT_TYPE = api]]; then echo "Deploy Stable nuget";
 # - if [[ $STABLE = false ]]; then echo "Deploy Unstable nuget";